'use client'
import './globals.css'

import {
  QueryClient,
  QueryClientProvider,

} from '@tanstack/react-query'

import { Toaster } from 'react-hot-toast'
//import '../../../files/admin_template/admin_template_321.css'
// import 'file:///C:/Users/user/Desktop/files/admin_template/admin_template_321.css'
import {  useState } from 'react'
import { useEffect } from 'react'



const queryClient = new QueryClient()
// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {

 
const [categories, setCategories] = useState([])
const [css, setCss] = useState([])


  useEffect(() => {
    fetch(`${process.env.NEXT_PUBLIC_API_URL}:5004/admin/admin_panel_settings`)
      .then(Response => Response.json())
      .then(data => setCategories(data))
  }, [])
  console.log(categories)



  const filteredCategories = categories.filter(category => category.status === 1);
  // console.log(filteredCategories[0], 'filteredCategories[0]?.admin_template')
// const adminTemplateCssPath = filteredCategories[0]?.admin_template || 'default-template'



  //  const bodyBgChange = localStorage.getItem("bodyBgChange")
  //  const bodyTextColourChange = localStorage.getItem("bodyTextColour")
  //{`http://192.168.0.112:5003/get-css-content/admin_template_321.css?v=${filteredCategories[0]?.version_code}`}
  // <link rel="preload" href="https://website.urbanitsolution.com/files/css/admin-template-9.css?v=4.2" as="style" />
  return (
    <html lang="en">
     
      <head>
        {/* <link rel="stylesheet" href="https://website.urbanitsolution.com/files/css/admin-template-9.css?v=4.2" />   */}
        
        <link rel="stylesheet" href={`${process.env.NEXT_PUBLIC_API_URL}:5003/get-css/${filteredCategories[0]?.admin_template}?v=${filteredCategories[0]?.version_code}`} />  
      </head>
      <body >
        <QueryClientProvider client={queryClient}>
          
          <Toaster></Toaster>
          
            {children}
         

        </QueryClientProvider>
      </body>
    </html>
    
  )
}
